In [8]:
import pandas as pd
import numpy as np
from faker import Faker
import random
from datetime import datetime, timedelta

fake=Faker()
random.seed(42)
np.random.seed(42)

In [5]:
!pip install faker

Collecting faker
  Downloading faker-40.23.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: tzdata in c:\users\mkcomputer\anaconda3\lib\site-packages (from faker) (2025.2)
Downloading faker-40.23.0-py3-none-any.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.0 MB ? eta -:--:--
   ---------- ----------------------------- 0.5/2.0 MB 1.3 MB/s eta 0:00:02
   -------------------- ------------------- 1.0/2.0 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------- 2.0/2.0 MB 2.8 MB/s  0:00:01
Installing collected packages: faker
Successfully installed faker-40.23.0

In [9]:
categories=  pd.DataFrame({
    'Category_id': range(1,9),
    'Category_name': ['Electronics', 'Clothing', 'Home & Kitchen',
        'Sports', 'Books', 'Beauty', 'Toys', 'Furniture']
})
categories

   Category_id   Category_name
0            1     Electronics
1            2        Clothing
2            3  Home & Kitchen
3            4          Sports
4            5           Books
5            6          Beauty
6            7            Toys
7            8       Furniture

In [12]:
customers= pd.DataFrame({
    'customer_id': range(1,501),
    'first_name': [fake.first_name() for _ in range(500)],
    'last_name':[fake.last_name() for _ in range(500)],
    'email': [fake.email() for _ in range(500)],
    'city': [fake.city() for _ in range(500)],
    'country': [fake.country() for _ in range(500)],
    'registration_date': [fake.date_between(start_date= '-3y', end_date= 'today') for _ in range(500)]
        
})
customers.head()

,customer_id,first_name,last_name,email,city,country,registration_date
0,1,Christopher,Davis,joshua52@example.org,New Courtneystad,Timor-Leste,2024-03-19
1,2,Tara,Dixon,douglas65@example.com,Kristiport,Vanuatu,2024-01-28
2,3,James,Chen,nancy22@example.net,Kevinview,Cocos (Keeling) Islands,2024-11-24
3,4,Amy,Newton,kanderson@example.com,South Paula,British Indian Ocean Territory (Chagos Archipe...,2024-02-19
4,5,Nicholas,Hammond,flynncarlos@example.org,Lesliechester,Kuwait,2025-04-03

In [14]:
f"Customers no: {len(customers)}"

'Customers no: 500'

In [16]:
products = pd.DataFrame({
    'product_id': range(1, 201),
    'product_name': [fake.catch_phrase() for _ in range(200)],
    'category_id': [random.randint(1, 8) for _ in range(200)],
    'price': [round(random.uniform(5, 500), 2) for _ in range(200)],
    'stock_quantity': [random.randint(0, 100) for _ in range(200)]
})

In [17]:
products.head()

,product_id,product_name,category_id,price,stock_quantity
0,1,Reactive motivating projection,1,445.26,24
1,2,Quality-focused 24/7 website,1,368.59,79
2,3,Re-engineered zero administration encoding,4,303.84,32
3,4,Innovative exuding archive,4,17.80,86
4,5,Customer-focused mobile utilization,1,118.32,96

In [18]:
f"Products no: {len(products)}"

'Products no: 200'

In [19]:
orders = pd.DataFrame({
    'order_id': range(1, 1001),
    'customer_id': [random.randint(1, 500) for _ in range(1000)],
    'order_date': [
        fake.date_between(start_date='-2y', end_date='today')
        for _ in range(1000)
    ],
    'status': [
        random.choice(['Completed', 'Pending', 'Cancelled', 'Refunded'])
        for _ in range(1000)
    ],
    'total_amount': [round(random.uniform(10, 2000), 2) for _ in range(1000)]
})

In [20]:
orders.head()

   order_id  customer_id  order_date     status  total_amount
0         1           56  2025-12-14  Cancelled       1391.12
1         2          232  2025-12-13   Refunded        960.62
2         3          258  2025-12-03    Pending        465.60
3         4          114  2024-10-26  Completed        187.77
4         5          485  2025-03-28  Completed       1613.85

In [21]:
f"Orders no: {len(orders)}"

'Orders no: 1000'

In [22]:
order_items = []

for order_id in range(1, 1001):
    num_items = random.randint(1, 5)
    products_chosen = random.sample(range(1, 201), num_items)
    
    for product_id in products_chosen:
        quantity = random.randint(1, 10)
        unit_price = round(random.uniform(5, 500), 2)
        order_items.append({
            'order_item_id': len(order_items) + 1,
            'order_id': order_id,
            'product_id': product_id,
            'quantity': quantity,
            'unit_price': unit_price
        })

order_items = pd.DataFrame(order_items)

In [24]:
order_items.head()

   order_item_id  order_id  product_id  quantity  unit_price
0              1         1         200         3       56.26
1              2         1          46        10      305.05
2              3         1         178         6      254.53
3              4         1         149         7      212.24
4              5         1          45        10      458.38

In [25]:
f"\nعدد الـ Order Items: {len(order_items)}"

'\nعدد الـ Order Items: 3005'

In [26]:
categories.to_csv('categories.csv', index= False)

In [28]:
customers.to_csv('customers.csv', index= False)

In [29]:
products.to_csv('products.csv', index= False)

In [30]:
orders.to_csv('orders.csv', index= False)

In [31]:
order_items.to_csv('order_items.csv', index= False)

In [32]:
print(f"Categories:  {len(categories)} rows")
print(f"Customers:  {len(customers)} rows")
print(f"Products:  {len(products)} rows")
print(f"Orders:  {len(orders)} rows")
print(f"Order Items:  {len(order_items)} rows")

Categories:  8 rows
Customers:  500 rows
Products:  200 rows
Orders:  1000 rows
Order Items:  3005 rows

In [33]:
print(categories)

   Category_id   Category_name
0            1     Electronics
1            2        Clothing
2            3  Home & Kitchen
3            4          Sports
4            5           Books
5            6          Beauty
6            7            Toys
7            8       Furniture

In [35]:
print(categories.to_csv('categories.csv', index=False))

PermissionError: [Errno 13] Permission denied: 'categories.csv'

In [36]:
print(open('categories.csv').read())

customer_id,first_name,last_name,email,city,country,registration_date
1,Christopher,Davis,joshua52@example.org,New Courtneystad,Timor-Leste,2024-03-19
2,Tara,Dixon,douglas65@example.com,Kristiport,Vanuatu,2024-01-28
3,James,Chen,nancy22@example.net,Kevinview,Cocos (Keeling) Islands,2024-11-24
4,Amy,Newton,kanderson@example.com,South Paula,British Indian Ocean Territory (Chagos Archipelago),2024-02-19
5,Nicholas,Hammond,flynncarlos@example.org,Lesliechester,Kuwait,2025-04-03
6,Mary,Gonzalez,zkeith@example.org,North Adam,Norfolk Island,2025-12-02
7,Ashley,Hill,uosborne@example.com,East Justin,Hungary,2024-07-03
8,Jeffery,Carter,whiteronald@example.com,Arthurburgh,Poland,2023-09-27
9,Jeremy,Watson,powellbrandon@example.com,Trujilloville,Kyrgyz Republic,2024-09-19
10,Edward,Neal,jonesapril@example.com,North Ernest,Macao,2023-07-27
11,Brian,Hudson,lhayes@example.org,Lake Samuel,Zambia,2023-07-08
12,Kyle,Fletcher,lindsay42@example.net,Wadestad,Ireland,2024-08-07
13,Joshua,Dillon,brittanywalker@example.net,West Matthewtown,Senegal,2025-05-08
14,Richard,Marshall,deborahtran@example.com,Wardchester,Uruguay,2024-01-04
15,Courtney,Hopkins,cynthiahall@example.net,Johnchester,Holy See (Vatican City State),2024-12-17
16,Diane,Fernandez,jamesmegan@example.org,Wilsonton,Singapore,2024-05-30
17,Tammy,Todd,danielwilson@example.org,Courtneyview,Albania,2024-10-03
18,Jeremiah,Hill,thomaskoch@example.org,Lake Joshua,Paraguay,2024-01-09
19,Samuel,Alexander,pmccoy@example.net,South Tara,North Macedonia,2024-10-11
20,Victoria,Wilson,joshuaharris@example.net,Mooreton,Dominica,2024-03-15
21,Alyssa,Stanley,gweaver@example.com,Lake Jayside,Brunei Darussalam,2025-07-17
22,William,Moss,fturner@example.com,South Thomaschester,Christmas Island,2025-08-17
23,Emily,Pacheco,carolynchambers@example.net,Alvaradoport,Svalbard & Jan Mayen Islands,2024-03-28
24,Steven,Braun,justinmoore@example.com,Nicholasmouth,Oman,2025-06-23
25,Christina,Guzman,fharris@example.com,Davidshire,Samoa,2023-09-13
26,Ethan,Stewart,petersonsamuel@example.org,New Codyside,Mexico,2025-02-27
27,Julie,Stevenson,christinamarshall@example.com,New Nicholasberg,Maldives,2025-09-24
28,Amanda,Knox,cross@example.org,South Jamesberg,Bahrain,2023-06-29
29,Brandon,Johnston,andrewsphillip@example.org,Timothyside,Micronesia,2024-09-19
30,Bruce,Evans,anthony67@example.org,Dianamouth,Lao People's Democratic Republic,2026-01-08
31,Richard,Weaver,ujohnson@example.com,Marksfort,Mauritius,2025-08-28
32,Jeremy,Hill,ugray@example.org,Gloverberg,Sweden,2026-01-16
33,Christopher,Lopez,shannonbaker@example.org,Bradleyfort,Cocos (Keeling) Islands,2024-10-19
34,James,Jones,timothy78@example.net,Georgeberg,Saint Helena,2024-01-21
35,Crystal,Knight,wgarcia@example.org,Johnmouth,Trinidad and Tobago,2024-06-18
36,Chelsea,Ortiz,kelly69@example.org,Danielfort,Western Sahara,2025-05-07
37,Karen,Mitchell,mosleyjeffrey@example.com,Petersbury,Israel,2024-07-15
38,Leslie,Butler,oproctor@example.com,East Ashleyhaven,Mayotte,2023-08-15
39,Keith,Woodward,vpayne@example.com,New Diamond,Marshall Islands,2026-02-06
40,Tracy,Calhoun,craigwilliams@example.org,Lake Steve,Venezuela,2024-02-10
41,William,Jensen,nicholasking@example.com,East Dianachester,Slovenia,2024-09-24
42,Jacob,Thomas,jamesrangel@example.com,East Crystalmouth,Seychelles,2025-03-01
43,Martin,Wilson,hbell@example.org,North Ronald,Austria,2024-10-06
44,Ryan,Rogers,michaelferguson@example.com,Emilystad,Turkmenistan,2024-02-04
45,Michael,Jackson,coxalex@example.net,Collinsshire,Spain,2025-01-11
46,Justin,Lucero,elizabeth91@example.com,Moralesside,Canada,2026-02-17
47,Erik,Kim,longjoseph@example.com,Aaronchester,Papua New Guinea,2025-10-16
48,Brandon,Watson,nthompson@example.net,Suemouth,Marshall Islands,2024-05-21
49,Jesse,Cooper,cbradley@example.org,East Josephhaven,Ecuador,2026-03-20
50,Chelsea,Thomas,mendezkimberly@example.org,South Lauraland,Kyrgyz Republic,2024-12-20
51,Jessica,Blackwell,cmendez@example.com,Chavezburgh,Kyrgyz Republic,2025-03-18
52,Ryan,Rich,lauriecraig@example.org,East Jasonshire,Japan,2023-11-17
53,Elizabeth,Marsh,lloydnatalie@example.net,Joelmouth,Croatia,2026-02-18
54,Barbara,Proctor,youngterri@example.com,Williamsonbury,American Samoa,2025-05-27
55,Phyllis,Hill,kbrock@example.org,South Jill,Guinea,2025-06-24
56,James,Bailey,lisaedwards@example.org,Martinezview,Albania,2024-04-02
57,Christopher,Steele,jacqueline71@example.net,Danieltown,Cameroon,2024-03-01
58,Deborah,Phillips,edward64@example.net,North Kimview,Turkey,2025-04-05
59,Brenda,Nunez,sandranewton@example.net,New Josephborough,Tuvalu,2024-08-28
60,Christina,Owens,zpowell@example.com,Lake Christopherport,Netherlands,2024-03-21
61,Seth,Evans,tanner88@example.org,Erinton,Antarctica (the territory South of 60 deg S),2025-08-19
62,Tammy,Gonzalez,bradyburgess@example.com,New Amber,Central African Republic,2024-12-02
63,Jonathan,Gonzales,juan68@example.com,South Tyler,Morocco,2025-04-12
64,Pamela,Davis,joseph12@example.com,Williammouth,Lao People's Democratic Republic,2025-12-28
65,Michelle,Moyer,xhill@example.org,West Tammiemouth,Antigua and Barbuda,2024-11-20
66,Patrick,Ramsey,franktaylor@example.org,Marshallberg,Oman,2025-04-10
67,Jeremy,Martinez,wardmary@example.com,Richardsonville,Korea,2024-02-03
68,Anthony,Hood,ohill@example.org,Haydenbury,Guam,2024-09-15
69,Michael,Pratt,kalvarez@example.net,Lake Kathleen,Morocco,2026-05-24
70,Thomas,Armstrong,grahamnatalie@example.net,Donnahaven,Algeria,2025-04-15
71,Kristin,Davis,ncobb@example.org,Albertfurt,Mongolia,2026-06-23
72,Ashley,Grant,vtorres@example.org,Duarteview,Malawi,2024-05-15
73,Sue,Ferguson,hhill@example.net,West Thomas,Chad,2024-12-09
74,Jason,Williams,richardritter@example.org,New Randall,France,2025-02-04
75,Michael,Bush,wwalsh@example.org,Alexanderfort,Dominican Republic,2023-10-15
76,Brooke,Freeman,schmidtamanda@example.net,South Edward,Cameroon,2026-06-15
77,Natalie,Robbins,adam12@example.net,East Caseyport,Saudi Arabia,2025-09-28
78,Aaron,Hodge,jonesjacob@example.org,New Jessicaborough,Norway,2025-01-05
79,Nancy,Vincent,barnesbradley@example.com,North Brian,Iceland,2024-03-14
80,Dennis,Liu,alexander18@example.net,Alvinstad,Pitcairn Islands,2023-06-29
81,Ashley,Williams,claynicole@example.org,Williamsmouth,Cameroon,2024-10-17
82,Miranda,Fernandez,rwhitaker@example.net,Hardingview,Syrian Arab Republic,2025-11-10
83,Jennifer,Martinez,kaitlyn33@example.com,Clarkview,Togo,2023-08-11
84,Julie,Levine,umiller@example.org,Carolinefort,Niue,2025-01-07
85,Jennifer,Dean,mahoneyheather@example.org,Clarkborough,British Virgin Islands,2025-07-25
86,Laura,Wise,jeffreymorgan@example.net,Lake Alyssa,Saint Lucia,2025-09-03
87,John,Lucas,zgallegos@example.org,Port Chelseaton,Puerto Rico,2024-10-05
88,Ashley,Campbell,ryan07@example.org,Lake Kevinland,Morocco,2025-09-21
89,David,Oliver,jessica70@example.com,New Michaelborough,Mongolia,2024-12-02
90,Gina,Moreno,ddavis@example.com,West Tamara,Saint Kitts and Nevis,2024-05-14
91,Tabitha,Small,james62@example.net,Geoffreyside,Ethiopia,2024-10-03
92,Sabrina,Randolph,zacharybautista@example.org,Chavezbury,Cayman Islands,2023-09-09
93,Rhonda,Horn,erik84@example.net,Nashchester,Martinique,2025-05-16
94,Steven,Carter,jonathan30@example.net,Martinville,Haiti,2023-12-15
95,Roy,Johnson,rachel20@example.net,Port Dawnfurt,Chile,2025-07-02
96,Ryan,Alvarado,alexanderhall@example.com,North Angelaland,Jordan,2024-03-08
97,Christopher,Anderson,wagnerkenneth@example.net,Port Nicholas,Reunion,2024-10-16
98,Patrick,Anderson,matthewwhite@example.com,Simpsonburgh,Samoa,2024-08-17
99,David,Chavez,james08@example.net,Martinezville,American Samoa,2026-06-08
100,Emily,Richardson,lindsey74@example.net,Angelaville,French Polynesia,2024-12-22
101,Danielle,Gonzalez,alexander50@example.org,East Marystad,Bermuda,2025-04-06
102,Jessica,Bush,brandonwebb@example.com,Newmanstad,Palestinian Territory,2025-05-12
103,Victor,Hampton,michelle00@example.org,Lake Dakota,Algeria,2023-10-11
104,Geoffrey,Gardner,jacquelinejuarez@example.com,West Johnhaven,Gambia,2024-10-21
105,Ann,Sandoval,daniel68@example.com,South Reginaldton,Togo,2026-05-23
106,Jared,Carter,alivictoria@example.net,Richardshire,Greenland,2026-02-06
107,Mary,Anderson,john07@example.org,Larahaven,Martinique,2024-01-26
108,Andrea,Ruiz,davisdaniel@example.org,Rachelmouth,Sweden,2025-11-03
109,Cynthia,Mendez,randallkevin@example.net,South Natalie,Uruguay,2023-11-26
110,Jennifer,Morris,cassienewton@example.org,South Jacob,Algeria,2023-11-16
111,Javier,Pierce,randy50@example.org,New Crystal,Papua New Guinea,2024-05-25
112,Morgan,Hogan,gchaney@example.org,Lake Anthonyhaven,Tanzania,2025-11-10
113,Andrea,Hubbard,owenssally@example.org,Sherichester,Armenia,2024-06-06
114,Robert,Khan,victoriadavidson@example.org,New Samanthabury,Kuwait,2024-12-16
115,Christy,Butler,hernandezanthony@example.com,Duncanmouth,Iran,2024-02-18
116,Paul,Taylor,acurry@example.com,Grayberg,Tokelau,2026-03-14
117,Julia,Thomas,alvaradochris@example.com,Madisonside,Lesotho,2023-08-31
118,Steven,Garcia,christianfernandez@example.net,Davidland,Panama,2024-11-27
119,Bradley,Medina,ffarmer@example.org,Catherineland,Tunisia,2025-07-02
120,Timothy,Ward,markmoore@example.org,North Janicemouth,Cuba,2026-03-20
121,Jason,Montoya,shawnandrews@example.net,Tiffanyfurt,Ethiopia,2024-08-20
122,Elizabeth,Ball,mitchellpriscilla@example.net,Denisefort,Botswana,2023-09-12
123,Brian,Moran,ttorres@example.net,Williamsmouth,Samoa,2025-12-28
124,Lauren,Kaufman,halltaylor@example.net,North Kimstad,Qatar,2024-05-25
125,Jennifer,Ward,nicholas79@example.com,New Danielburgh,Gibraltar,2026-01-24
126,Maria,David,hgamble@example.com,East Heidishire,Indonesia,2024-06-21
127,Nancy,Smith,randalltina@example.org,Georgebury,Oman,2023-07-10
128,Gail,Harrison,kristie96@example.org,New James,Turkey,2025-12-27
129,Jerry,Delgado,meghan06@example.org,Davidbury,Cambodia,2024-05-01
130,Darren,Horne,linda09@example.net,South Barryview,Moldova,2026-03-31
131,John,Miller,anthonytanner@example.net,Port Marcus,Monaco,2025-06-16
132,Billy,Hines,ana80@example.net,West Sarahland,Christmas Island,2024-03-18
133,Kendra,Stevens,weaverchristopher@example.net,Mcgrathborough,Djibouti,2024-12-03
134,Cheryl,Porter,woodscheryl@example.net,Brownside,Guadeloupe,2025-08-13
135,Bruce,George,sarahcoleman@example.net,East Jessicamouth,Czech Republic,2025-02-27
136,Matthew,Reed,valeriewilson@example.org,Wilsonfurt,Hong Kong,2026-05-18
137,Natasha,Morgan,holdenryan@example.net,Cainburgh,Samoa,2025-07-19
138,Aaron,Martinez,vjohnson@example.org,Maryton,Wallis and Futuna,2026-02-10
139,Michael,Clark,leejason@example.com,Taramouth,Mali,2025-05-08
140,Janet,Bennett,boydcolleen@example.net,Myersville,Liechtenstein,2025-10-29
141,Michael,Hernandez,michaelthompson@example.org,Lake Clifford,Western Sahara,2023-10-04
142,Melanie,Vazquez,vbest@example.org,Huffmanport,Jamaica,2024-10-29
143,Samuel,Castro,ian29@example.com,Sextonfurt,Slovakia (Slovak Republic),2025-10-12
144,Angela,Owens,chowell@example.org,South Monica,Bahamas,2026-03-05
145,David,Cantu,shannonchandler@example.com,Lake Haileyville,Croatia,2026-04-29
146,Mark,Hunter,tanya78@example.com,Amberland,Switzerland,2024-11-01
147,Jennifer,Freeman,hstevenson@example.net,New Johnville,Finland,2026-01-01
148,Brittany,Baker,brianparker@example.net,Jesseton,Grenada,2025-01-08
149,James,Jackson,ikeith@example.org,New Tinachester,Namibia,2024-03-12
150,Steven,Thomas,robert55@example.org,New Patricia,Venezuela,2023-10-11
151,Jennifer,Watson,brittanybarber@example.com,Port Annmouth,French Polynesia,2024-01-17
152,Sharon,Bryan,zbaker@example.com,Lake Danielle,Marshall Islands,2025-08-04
153,Justin,Woods,jamessullivan@example.org,New Lydiaton,Svalbard & Jan Mayen Islands,2025-07-01
154,Kathryn,Meyer,jerrybrock@example.net,Elizabethfurt,Holy See (Vatican City State),2025-09-14
155,Victoria,Williams,megancarr@example.com,Lake Jasonshire,Ghana,2025-06-07
156,Alexander,Lin,austinrivers@example.net,Jimenezshire,Christmas Island,2026-02-11
157,Pamela,Singh,volson@example.org,South Alexander,Mayotte,2023-09-09
158,Marilyn,Guerrero,dorothy16@example.net,Lake Timothyfurt,Jersey,2025-05-08
159,Allison,Vaughn,pearsonjason@example.com,Derrickmouth,Lithuania,2025-04-26
160,Ronald,Warren,pcoleman@example.org,East Ericview,Kuwait,2024-01-30
161,Brittany,Davis,youngmegan@example.net,Lake Timothyfort,Costa Rica,2024-01-17
162,Beth,Garcia,steven02@example.com,Fieldsstad,Korea,2024-11-26
163,Nicholas,Lewis,blake88@example.org,Brandyville,Saint Barthelemy,2024-07-20
164,Garrett,Chung,cooperandrew@example.com,Nicholasmouth,Malta,2025-08-18
165,Jim,Gross,kmartinez@example.org,East Michealberg,Malta,2023-08-12
166,Emily,Gould,mle@example.net,South Cassie,United States Virgin Islands,2025-09-14
167,Manuel,Smith,hansonomar@example.com,Lake Jacobfurt,Croatia,2026-01-09
168,Tiffany,Vance,whitepatricia@example.org,Andreaville,Taiwan,2024-02-08
169,Michele,Davis,fbryant@example.com,Jasonmouth,Latvia,2026-04-26
170,Yolanda,Aguilar,juliemorris@example.org,Riverastad,Malta,2026-02-12
171,Calvin,Mendez,robindavenport@example.net,Jenniferland,Central African Republic,2025-10-20
172,Tanya,Sanchez,qcarpenter@example.com,Barnetthaven,Pitcairn Islands,2025-01-14
173,Susan,Diaz,ramirezdavid@example.net,East Nicholaston,Micronesia,2025-03-22
174,Latasha,Zavala,amy46@example.com,Lauramouth,Palau,2025-07-04
175,Michele,Brennan,craig22@example.com,South Johnton,Pakistan,2024-11-01
176,Cynthia,Rios,oneal@example.net,Youngmouth,Suriname,2023-07-26
177,Danielle,Sandoval,amber49@example.org,Donnafurt,Latvia,2025-07-13
178,Nathan,White,knappjennifer@example.com,New Taylor,Lesotho,2025-09-12
179,Karen,Taylor,daltonhuang@example.net,Lake Justinside,Martinique,2024-03-04
180,Ashley,Waters,anthonymeadows@example.org,Schaeferfurt,Burkina Faso,2025-09-17
181,Ian,Bailey,joshuamckenzie@example.net,Masonborough,Nicaragua,2025-06-23
182,Ricardo,Ross,ashleyburnett@example.net,South Bethany,Tunisia,2025-08-07
183,Linda,Hendricks,jennastephens@example.org,Keithville,Western Sahara,2025-07-13
184,Adriana,Valenzuela,cbarry@example.net,Floydstad,Egypt,2025-09-21
185,Fernando,Meyer,james34@example.org,South Gabriel,Libyan Arab Jamahiriya,2025-02-07
186,Randy,Hernandez,guzmanrodney@example.net,East Rebeccaville,Swaziland,2024-06-08
187,Elaine,Reynolds,jordanhernandez@example.net,Lucasmouth,Canada,2025-12-29
188,Thomas,Ramirez,brian60@example.net,Lyonschester,Croatia,2024-11-28
189,Amy,Parker,frank04@example.org,South Kristin,Senegal,2023-11-23
190,Gary,Gilmore,oduran@example.net,West Jacob,Falkland Islands (Malvinas),2025-11-08
191,Anthony,Oconnor,vgreen@example.net,Fullerfort,Netherlands,2026-05-10
192,Sandra,Stanton,zrobertson@example.net,East Brittanyshire,Portugal,2026-05-27
193,Tyler,Newman,vcarrillo@example.com,Port Barrytown,Suriname,2025-01-27
194,Jennifer,Buckley,limark@example.com,Westshire,Guernsey,2023-12-09
195,Carrie,Hall,cody75@example.com,North Rachel,Malta,2025-11-18
196,Michael,Guerra,kara23@example.com,South Amandaton,Nicaragua,2026-03-21
197,Emily,Castillo,campbelldavid@example.org,West Josephside,Canada,2024-01-19
198,Erica,Terrell,jorgeprice@example.com,Baileystad,Martinique,2026-06-14
199,Aaron,White,davidsonphillip@example.com,New Sandraville,Maldives,2024-12-02
200,Debra,Cruz,masonsheryl@example.net,Georgeburgh,Tokelau,2025-09-15
201,Danny,Christensen,amanda16@example.com,South Amymouth,Cuba,2024-04-06
202,Susan,Dickerson,john34@example.org,Whiteberg,Norway,2025-08-31
203,Darren,Hernandez,denniskidd@example.com,Erinton,Slovenia,2025-01-16
204,Adam,Miller,elizabeth20@example.org,New Rachel,Latvia,2026-02-18
205,Jeffrey,Jarvis,rdiaz@example.com,Michaelmouth,Central African Republic,2023-09-18
206,Ashley,Crane,william59@example.com,New Kristen,Honduras,2025-10-02
207,Sean,Sullivan,chad91@example.com,East Kennethton,Jersey,2025-01-01
208,Ashley,Brown,oneilldonna@example.org,Barnesmouth,Madagascar,2024-07-21
209,Daniel,Wood,jerry18@example.com,Robertsbury,Bhutan,2025-02-24
210,Jasmine,Willis,obrennan@example.com,Smithborough,Cyprus,2026-04-15
211,Gary,Reynolds,mannjustin@example.com,Dianebury,Northern Mariana Islands,2025-08-14
212,Justin,Walker,pmiller@example.org,West Monique,Kenya,2026-06-20
213,Jessica,Reyes,meyerdiana@example.org,South Amanda,Nigeria,2026-02-17
214,Jacqueline,Kennedy,ryantravis@example.org,East Ashley,Isle of Man,2026-01-24
215,Frank,Johnson,grantjessica@example.net,Port Michaelchester,Mauritius,2026-01-06
216,Jonathan,Anderson,hayley58@example.org,Cookfort,Saint Barthelemy,2024-11-19
217,Erica,Brown,michael69@example.com,North Richardhaven,Saint Pierre and Miquelon,2025-11-16
218,Teresa,Pruitt,qfrancis@example.org,East Stephanie,Western Sahara,2024-01-19
219,Kelsey,Townsend,keithjoshua@example.net,Morrowmouth,Germany,2025-10-08
220,Michele,Reyes,umendez@example.net,Rodriguezhaven,Cyprus,2026-04-01
221,Anthony,Steele,anthony24@example.org,Sellersview,Guadeloupe,2024-04-02
222,Steven,Terry,jeffreymarshall@example.com,Amyland,United Arab Emirates,2023-09-11
223,Matthew,Mendez,wadams@example.com,New Christine,Monaco,2024-12-19
224,Kendra,Williams,tcasey@example.com,Port Crystal,Ecuador,2024-06-20
225,Jeffrey,Romero,brandy13@example.org,East Franciscoville,Mauritius,2023-10-07
226,Jennifer,Johnson,patriciamiller@example.org,South Andrea,Latvia,2024-06-05
227,Gerald,Frank,williamsonnancy@example.org,North Davidmouth,Saint Barthelemy,2024-01-09
228,Sarah,Blake,zjenkins@example.net,Elizabethfurt,American Samoa,2023-07-09
229,Benjamin,Moore,michele70@example.com,South Rachelland,Sao Tome and Principe,2024-11-11
230,Robert,Martinez,yoderjennifer@example.org,Richardland,Chile,2025-08-20
231,Cassidy,Simpson,colemanwalter@example.org,East Jaredland,Kiribati,2024-06-10
232,George,Wheeler,anntran@example.com,Bishopstad,Gibraltar,2025-06-20
233,Joseph,Martin,hernandezmegan@example.com,Karenfort,Holy See (Vatican City State),2025-11-24
234,Joshua,Mcneil,andrew25@example.net,North Davidstad,Aruba,2025-10-01
235,James,Mcintosh,danielnguyen@example.com,West Jaclyn,Philippines,2026-04-25
236,Dawn,Mckee,zramirez@example.net,New Craig,Tokelau,2024-10-18
237,Paul,Gray,leslie84@example.com,West Michael,Tanzania,2026-02-17
238,Joseph,Yu,danny32@example.com,East Nicholas,Holy See (Vatican City State),2025-12-18
239,Elizabeth,Miller,leonardbranch@example.net,Robinsonton,Fiji,2025-05-08
240,Alan,Watkins,callahanscott@example.com,New Julie,Finland,2026-02-23
241,Nicholas,Lee,ujohnson@example.com,Lake Charlesmouth,Latvia,2024-06-22
242,Joseph,Aguirre,kimberly79@example.org,Brooksshire,Uzbekistan,2026-01-06
243,Kathryn,Humphrey,uchavez@example.net,West Douglas,Ghana,2024-03-12
244,Rachel,Nelson,latoyawebb@example.com,Tiffanyville,Jamaica,2024-10-25
245,Ian,Hall,richardsonkaren@example.net,Copelandmouth,Faroe Islands,2025-12-31
246,Michelle,Stewart,rayjoshua@example.com,Lake Scott,Cocos (Keeling) Islands,2025-05-27
247,Scott,Coleman,cherylmurray@example.org,Gonzalesview,Hong Kong,2024-06-28
248,James,Miller,rjames@example.com,East Patriciamouth,San Marino,2025-01-01
249,John,Macdonald,mckinneyjessica@example.org,Amberchester,India,2023-07-15
250,Andrea,Scott,baileydenise@example.net,Amytown,Mayotte,2025-03-11
251,Andre,Nicholson,markgonzalez@example.net,Charleston,Sierra Leone,2025-03-23
252,Adam,Mccoy,benjamin47@example.com,Kaylaland,Gambia,2024-05-14
253,Kevin,Howard,sanchezdevin@example.net,West Nancy,Czech Republic,2025-10-07
254,Raymond,Ward,jstewart@example.net,Lake Kimberlyshire,Luxembourg,2024-06-10
255,Sandra,Hays,fordrobert@example.org,East Alexandratown,Kyrgyz Republic,2025-09-17
256,Noah,Sanchez,rodriguezedward@example.org,Marshallville,Mexico,2026-01-27
257,George,Humphrey,becky60@example.net,Oliviaville,Switzerland,2023-12-03
258,Rachel,Serrano,hamiltonemily@example.org,New Christopher,Kyrgyz Republic,2024-10-23
259,James,Jones,brian24@example.com,Hernandezbury,Georgia,2024-10-17
260,Steve,Wilson,jeffrey07@example.com,North Deanhaven,Equatorial Guinea,2025-11-25
261,Laura,Phillips,jameswu@example.net,Monroeland,Kuwait,2025-11-27

In [37]:
type(categories)

pandas.core.frame.DataFrame

In [38]:
categories.head()

   Category_id   Category_name
0            1     Electronics
1            2        Clothing
2            3  Home & Kitchen
3            4          Sports
4            5           Books

In [39]:
import os
print(os.getcwd())

C:\Users\MKcomputer\Documents\E-Commerce_Data_Analysis

In [41]:
categories.to_csv(r'C:\Users\MKcomputer\Documents\E-Commerce_Data_Analysis\categories.csv', index=False)

In [42]:
print(open(r'C:\Users\MKcomputer\Documents\E-Commerce_Data_Analysis\categories.csv').read())

Category_id,Category_name
1,Electronics
2,Clothing
3,Home & Kitchen
4,Sports
5,Books
6,Beauty
7,Toys
8,Furniture

In [43]:
path = r'C:\Users\MKcomputer\Documents\E-Commerce_Data_Analysis\\'

customers.to_csv(path + 'customers.csv', index=False)
products.to_csv(path + 'products.csv', index=False)
orders.to_csv(path + 'orders.csv', index=False)
order_items.to_csv(path + 'order_items.csv', index=False)

print("✅ كل الملفات اتحفظت بنجاح!")

✅ كل الملفات اتحفظت بنجاح!